-- SND//WCH — LA FOTO DEL ESQUEMA COMPLETO (2026-09-24).
--
-- Devuelve, en una sola fila y columna (`ddl`), el SQL que reconstruye el esquema `public` tal
-- como está HOY en la base: secuencias, tablas con sus columnas y valores por defecto,
-- restricciones, índices, funciones, triggers, RLS y permisos.
--
-- POR QUÉ EXISTE. Las migraciones de supabase/migrations/ NO reconstruyen la base: la primera
-- (2026-04-24) ya agrega columnas a `customers`, una tabla que ninguna migración crea. Las tablas
-- originales nacieron desde el panel de Supabase, antes de que existiera el historial. Así que
-- «restaurar = aplicar las migraciones y cargar los datos» no funcionaba, y tampoco se podía
-- levantar un Postgres de pruebas con el esquema real. Se descubrió el 2026-09-24 al intentarlo.
--
-- Se corre contra la base real (execute_sql, o la Management API en CI) y el resultado se guarda
-- en supabase/esquema-actual.sql. `npm run check:pg` lo carga en un Postgres local.
with
sec as (
  select 1 as orden, s.sequencename as clave,
    format('create sequence if not exists public.%I as %s increment %s minvalue %s maxvalue %s start %s%s;',
      s.sequencename, s.data_type, s.increment_by, s.min_value, s.max_value, s.start_value,
      case when s.cycle then ' cycle' else '' end) as ddl
  from pg_sequences s
  join pg_class c on c.relname = s.sequencename
  join pg_namespace n on n.oid = c.relnamespace and n.nspname = s.schemaname
  where s.schemaname = 'public'
    -- las de columnas identity las crea la propia columna
    and not exists (select 1 from pg_depend d where d.objid = c.oid and d.deptype = 'i')
),
tab as (
  select 2, c.relname,
    format(E'create table public.%I (\n%s\n);', c.relname, string_agg(
      format('  %I %s%s%s%s', a.attname, format_type(a.atttypid, a.atttypmod),
        case a.attidentity when 'a' then ' generated always as identity' when 'd' then ' generated by default as identity' else '' end,
        case when a.attgenerated = 's' then ' generated always as (' || pg_get_expr(d.adbin, d.adrelid) || ') stored'
             when d.adbin is not null then ' default ' || pg_get_expr(d.adbin, d.adrelid) else '' end,
        case when a.attnotnull then ' not null' else '' end),
      E',\n' order by a.attnum))
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef d on d.adrelid = c.oid and d.adnum = a.attnum
  where n.nspname = 'public' and c.relkind = 'r'
  group by c.relname
),
duena as (
  select 3, s.relname,
    format('alter sequence public.%I owned by public.%I.%I;', s.relname, t.relname, a.attname)
  from pg_depend d
  join pg_class s on s.oid = d.objid and s.relkind = 'S'
  join pg_class t on t.oid = d.refobjid
  join pg_attribute a on a.attrelid = t.oid and a.attnum = d.refobjsubid
  join pg_namespace n on n.oid = s.relnamespace
  where n.nspname = 'public' and d.deptype = 'a'
),
res as (
  select case when co.contype = 'f' then 5 else 4 end, c.relname || '.' || co.conname,
    format('alter table public.%I add constraint %I %s;', c.relname, co.conname, pg_get_constraintdef(co.oid))
  from pg_constraint co
  join pg_class c on c.oid = co.conrelid
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and co.contype in ('p', 'u', 'c', 'f', 'x')
),
ind as (
  select 6, i.indexname, i.indexdef || ';'
  from pg_indexes i
  where i.schemaname = 'public'
    and not exists (select 1 from pg_constraint co where co.conname = i.indexname)
),
fun as (
  select 7, p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')', pg_get_functiondef(p.oid) || ';'
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind in ('f', 'p')
),
facl as (
  select 8, p.proname || '(' || pg_get_function_identity_arguments(p.oid) || ')',
    format('revoke all on function public.%I(%s) from public;', p.proname, pg_get_function_identity_arguments(p.oid))
    || coalesce((select string_agg(format(' grant execute on function public.%I(%s) to %s;', p.proname,
         pg_get_function_identity_arguments(p.oid), case when x.grantee = 0 then 'public' else quote_ident(r.rolname) end), '' order by r.rolname)
       from aclexplode(p.proacl) x left join pg_roles r on r.oid = x.grantee
       where x.privilege_type = 'EXECUTE'), '')
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prokind in ('f', 'p') and p.proacl is not null
),
trg as (
  select 9, c.relname || '.' || t.tgname, pg_get_triggerdef(t.oid) || ';'
  from pg_trigger t join pg_class c on c.oid = t.tgrelid join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and not t.tgisinternal
),
rls as (
  select 10, c.relname, format('alter table public.%I enable row level security;', c.relname)
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity
),
pol as (
  select 11, p.tablename || '.' || p.policyname,
    format('create policy %I on public.%I as %s for %s to %s%s%s;', p.policyname, p.tablename, p.permissive, p.cmd,
      array_to_string(p.roles, ', '),
      case when p.qual is not null then ' using (' || p.qual || ')' else '' end,
      case when p.with_check is not null then ' with check (' || p.with_check || ')' else '' end)
  from pg_policies p where p.schemaname = 'public'
),
tacl as (
  select 12, c.relname || '.' || coalesce(r.rolname, 'public'),
    format('grant %s on table public.%I to %s;', string_agg(x.privilege_type, ', ' order by x.privilege_type), c.relname,
      case when x.grantee = 0 then 'public' else quote_ident(r.rolname) end)
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  cross join lateral aclexplode(c.relacl) x
  left join pg_roles r on r.oid = x.grantee
  where n.nspname = 'public' and c.relkind = 'r' and c.relacl is not null
    and (r.rolname is null or r.rolname in ('anon', 'authenticated', 'service_role'))
  group by c.relname, x.grantee, r.rolname
),
todo as (
  select * from sec union all select * from tab union all select * from duena union all select * from res
  union all select * from ind union all select * from fun union all select * from facl union all select * from trg
  union all select * from rls union all select * from pol union all select * from tacl
)
select string_agg(ddl, E'\n\n' order by orden, clave) as ddl from todo;
